(defdb soggetti 
    (id-sini (random-unique))
  (id-sogg (random-number 1 100))
  (d-anno-accad (random-number 2010 2017))
  (d-mese-accad (random-number 1 12))
  (d-flg-coinvolto (random-boolean))
  (d-flg-richiedente (random-boolean))
  (d-flg-proprietario (random-boolean))
  (d-flg-contraente (random-boolean))
  (d-flg-coducente (random-boolean))
  (d-flg-trasporarto (random-boolean))
  (d-flg-pedone (random-boolean))
  (d-flg-leso (random-boolean))
  (d-flg-deceduto (random-boolean))
  (d-flg-testimone (random-boolean))
  (d-flg-medico (random-boolean))
  (d-flg-legale (random-boolean))
  (d-flg-carrozziere (random-boolean))
  (d-flg-respons (random-boolean))
  (d-flg-beneficiario (random-boolean))
  (d-flg-patente-invalida (random-boolean))
  (d-flg-grado-invalid (random-number 1 4))
  (m-num-senza-seg (random-number 1 10))
  (m-num-veic (random-number 1 10))
  (m-num-rich (random-number 1 10))
  (m-num-rich-fgvs (random-number 1 10))
  (m-num-tot-pagamenti (random-number 1 10))
  (m-num-tot-importo-les (random-number 1 10))
  (m-num-num-lesioni (random-number 1 10))
  (m-num-gg-da-decorrenza (random-number 1 10))
  (m-num-gg-a-decorrenza (random-number 1 10))
  (m-ultimo-agg (random-date (encode-universal-time 0 0 0 10 2 2017) (encode-universal-time 0 0 0 12 2 2017))))



(defdb veicoli 
    (id-sini (random-from (field-values *soggetti-table* :id-sini)))
  (id-targa (random-unique))
  (d-num-targa (random-string 7))
  (d-tipo-veic (random-string 1))
  (d-anno-accad (random-number 2010 2017))
  (d-mese-accad (random-number 1 12))
  (d-comune-accad (random-string 10))
  (d-tipo-targa (random-string 1)) 
  (d-cod-impr-ass (random-string 5))
  (d-flg-black-box (random-boolean))
  (d-flg-senza-conducente (random-boolean))
  (d-flg-targa-incoerente (random-boolean))
  (d-flg-targa-inesistente (random-boolean))
  (d-flg-veic-cessato (random-boolean))
  (m-num-danni (random-number 1 5))
  (m-tot-importo-veic (random-number 1 5))
  (m-num-rich (random-number 1 5))
  (m-num-rich-fgvs (random-number 1 5))
  (m-num-prop (random-number 1 5))
  (m-anni-immatr (random-number 1 5))
  (m-num-incoerenze (random-number 1 5))
  (m-ultimo-agg (random-date (encode-universal-time 0 0 0 10 2 2017) (encode-universal-time 0 0 0 12 2 2017))))


(defdb sinistri
    (id-sini (random-from (field-values *soggetti-table* :id-sini)))
  (d-data-accad (random-date (encode-universal-time 0 0 0 10 2 2017) (encode-universal-time 0 0 0 12 2 2017)))
  (d-comune-accad (random-string 10))
  (d-flg-autorita (random-boolean))
  (d-flg-pedoni (random-boolean))
  (d-flg-danni-ogg (random-boolean))
  (d-data-denun (random-date (encode-universal-time 0 0 0 10 2 2017) (encode-universal-time 0 0 0 12 2 2017)))
  (m-num-imprese (random-number 1 10))
  (m-num-soggetti (random-number 1 10))
  (m-num-coinvolti (random-number 1 10))
  (m-num-interessati (random-number 1 10))
  (m-num-rich (random-number 1 10))
  (m-num-veic (random-number 1 10))
  (m-num-senza-seg (random-number 1 10))
  (m-num-danno-veic (random-number 1 10))
  (m-num-lesi (random-number 1 10))
  (m-num-trasp-les  (random-number 1 10))
  (m-num-decessi (random-number 1 10))
  (m-num-invalid (random-number 1 10))
  (m-tot-pagamenti (random-number 1 10))
  (m-tot-importo-veic (random-number 1 10))
  (m-tot-importo-les (random-number 1 10))
  (m-tot-importo-ogg (random-number 1 10))
  (m-num-incoerenze (random-number 1 10))
  (m-gg-da-decorrenza (random-number 1 10))
  (m-gg-a-scadenza (random-number 1 10))
  (m-ultimo-agg (random-date (encode-universal-time 0 0 0 10 2 2017) (encode-universal-time 0 0 0 12 2 2017))))

(random-soggetti-table 1000)
(random-veicoli-table 1000)
(random-sinistri-table 1000)
